### ISSUE TITLE
Malformed usercss file

### ISSUE THREAD

**Issue by Neo-AzTeK** [ayebrian/themes#1]
The chatGPT usercss is malformed at the end. It is:
```css
@media (hover: hover) and (pointer: fine) {
     .btn-primary:hover:is(.dark *) {
         background-color: var(--scroll-bg);
     }
 }
 }

 .dark\:prose-invert:is(.dark *) :where(code):not(:where([class~=not-prose] *)) {
     background-color: var(--disabled-button-bg);
 }
```
But should be:
```css
 @media (hover: hover) and (pointer: fine) {
     .btn-primary:hover:is(.dark *) {
         background-color: var(--scroll-bg);
     }
 }
 .dark\:prose-invert:is(.dark *) :where(code):not(:where([class~=not-prose] *)) {
     background-color: var(--disabled-button-bg);
 }
 }
```
As such the rule to apply the style is not properly followed.
This causes the theme to be injected to all websites.
